### PR TITLE
Work on RC 1.12.x

### PR DESCRIPTION
**Pull request by Dockter**
I am continuing to test primarily world generation both in-dev and production (compiled), in combination with:
- Almura 3.0
- Bibliocraft
- Buildcraft 8.0.x dev builds
- CodeChickenLib
- CookingForBlockheads
- CustomMobSpawner
- CustomNPC's
- DrZharks MoCreatures
- Furniture 4.2.0-dev builds
- IC2, build 1.12.2 b75+ 
- InventoryTweaks
- IronBackpacks
- JEI
- Liteloader
- Malisiscore, MalisisDoors
- Mantle
- NotEnoughItems
- OptiFine 1.12.2 HD U D1 or higher
- PaydirtWash Plant
- SGCraft (AlmuraDev Version)
- SpongeForge (bleeding development builds on API 7.1.0)
- TConstruct
- WorldEdit

I am also using Advanced Xray to visual see ore generation rates without enabling skygen.

### CODE REVIEW

**Comment by Dockter** [comment]
Visual view of Poor Silver Ore (Red) and Silver Ore (light purple)
image

**Comment by Dockter** [comment]
Tin Generation using a slightly modified configuration values for s:core and s:fringe
image

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
Are those null checks really the way to fix?

**Comment by Dockter** [comment]
Null checking these was suggested by @Zidane since vanilla is doing it so he assumed the base code had some oddities that could generate nulls at this point of gen.

**Pull request merged**
