### PR TITLE
Submited the textures for the furnaces on RC

### PR DESCRIPTION
**Pull request by cabralRodrigo**
Ref: https://github.com/CovertJaguar/Railcraft/issues/246

### CODE REVIEW

**Comment by CovertJaguar** [comment]
@Yopu I'll let you handle this, not sure if you want to combine the textures into micro-sheets like most other RC blocks or leave them as individual files. I'll let you decide.

**Comment by Ristellise** [comment]
any update to this?

**Comment by liach** [comment]
Should these get cherry picked?

**Comment by CovertJaguar** [comment]
You can approve PRs? Hmm....didn't expect that.

**Comment by CovertJaguar** [comment]
You can add them if you want, its still an open project.

**Comment by CovertJaguar** [comment]
Why does it still query clahub?

**Comment by AEnterprise** [comment]
he's a collaborator to the repo so that automaticly gives him push rights to the repo and with that comes the ability to close issues/pr's and merge pr's

i'm guessing clahub is still queried cause this is an older pr from when you where still using it?

**Comment by CovertJaguar** [comment]
The Branch is protected though, I was expecting it to require an administrator review.

**Comment by AEnterprise** [comment]
he has write access so his aproving review counts for that

**Comment by CovertJaguar** [comment]
Can you review your own PRs? I wonder.

**Comment by liach** [comment]
Well, I cannot merge 🤷‍♂️

**Comment by liach** [comment]
No, people cannot give their own pull requests approved reviews, but can comment on them and count as contributions

**Comment by CovertJaguar** [comment]
Weird system, but ok.

**Comment by CovertJaguar** [comment]
I don't see much point in merging this directly, the naming of the files is inconsistent and weird. I'd say leave it unless you want to finish the Furnace block and make a new complete PR.

**Comment by Generalcamo** [comment]
This seems like it could be expanded beyond "Furnace Variant" to me. Smelt Time, Fuel Cost, and its derivative Efficiency could easily be applied to this.

If this is still desired, I personally would like to recreate the textures from scratch rather than reusing some from a ripped image.

**Comment by liach** [comment]
@Generalcamo Open project, feel free to do on your own.

**Comment by Generalcamo** [comment]
Close this one then, I'll make a new one if I decide to tackle it.

**Comment by liach** [comment]
Will close one if yours come up

**Comment by liach** [comment]
@Generalcamo Are you going to handle this?

**Comment by Generalcamo** [comment]
Not a priority at the moment @liach

**Pull request merged**
