### PR TITLE
Fixes #1137

### LINKED ISSUE #1137: Minecart Hopper Issues
1. when you open the inventory of the hopper minecart, it displays its unlocalised names
2. Hopper carts do not pull items froma block above.. though this might be a vanilla bug, if would be nice if wd could reimplement it back.

### PR DESCRIPTION
**Pull request by liach**
Deleted some stupid vanilla code. Lol.

### CODE REVIEW

**Comment by CovertJaguar** [comment]
How does removing the throttle make things better?

**Review by CovertJaguar — COMMENTED** [review]
How does removing the throttle make things better or fix the referenced issue?

**Comment by liach** [comment]
That thorttle code is useless. Now the cart can pick up a lot of item stacks.

**Comment by CovertJaguar** [comment]
That changes vanilla behavior though right?

**Comment by liach** [comment]
Well, vanilla ones I've not used them. Changed based on @Joshwoo70's comments

**Comment by liach** [comment]
I doubt that forge iitemhandler might have broken minecarts.

**Comment by CovertJaguar** [comment]
Hmm...I guess I need to test this in game and see if I can figure out what changed that created @Joshwoo70's issue.

**Comment by liach** [comment]
Both checks have died. @CovertJaguar lol

**Comment by liach** [comment]
Yes, travis works now

**Comment by liach** [comment]
Cleaned up the pull a little bit.

**Comment by liach** [comment]
@CovertJaguar Done. Reverted to vanilla behavior.

**Review by CovertJaguar — APPROVED** [review]

**Pull request merged**
