### PR TITLE
Crowbar events

### LINKED ISSUE #547: Throw some forge events when crowbar breaking blocks
It seems that the breaking function of the crowbar doesn't call any event. Maybe call some would improve compatibility.

### PR DESCRIPTION
**Pull request by liach**
Fixes #547

### CODE REVIEW

**Comment by liach** [comment]
Is this okay?

**Comment by CovertJaguar** [comment]
I have no plans to release another 1.7 version at this time.

**Comment by liach** [comment]
I agree that we need to focus on minecraft 1.10.2. I'd just leave this pr here as it is, until a stable version of Railcraft 10 is published probably.

**Comment by liach** [comment]
May I build a jar from this patch and use in a server and its mod pack? I will add a password lock to its mod pack. I want your permission.

**Comment by AEnterprise** [comment]
i think you could get away with just putting this on the server, as far as i see this is code that is/should only be executed on the server side

**Pull request merged**
