### PR TITLE
Organize Licenses

### PR DESCRIPTION
**Pull request by liach**

### CODE REVIEW

**Comment by CovertJaguar** [comment]
What is this?

**Comment by liach** [comment]
@CovertJaguar The build failed because the API is not formatted yet.

**Comment by Generalcamo** [comment]
I appreciate the standardization, I do support this. Though it's not really my license to approve/disapprove, so I took myself off the reviewers.

**Review by CovertJaguar — CHANGES_REQUESTED** [review]
No explanation/description == no merge.

**Comment by liach** [comment]
Wait a bit... Still working.

**Comment by liach** [comment]
I will remake one later.

**Pull request closed without merging**
