### PR TITLE
Updated nickel textures

### PR DESCRIPTION
**Pull request by Generalcamo**
These are updated textures for nickel. The old textures have received criticism that it looked too "golden." These new textures dull it slightly and has received good feedback thus far.

### CODE REVIEW

**Comment by liach** [comment]
The mc branch is messed up. I will change this to indev for now.

**Comment by liach** [comment]
Honestly, I'd keep this open and wait till cj finishes reorganization. Then I'll probably cherry-pick the commit.

**Review by liach — APPROVED** [review]

**Comment by CovertJaguar** [comment]
Just leave it alone. No cherry picking required. The indev branch is a dead branch at this point.

**Comment by liach** [comment]
will wait till you push.

**Review by CovertJaguar — APPROVED** [review]

**Pull request merged**
