### PR TITLE
Migrated to Forge Energy

### PR DESCRIPTION
**Pull request by liach**
Removed RF api interfaces, but it is kept for buildcraft API
See #1203

### CODE REVIEW

**Comment by CovertJaguar** [comment]
I was more planning to remove entirely rather than switch to the equally horrible FU, except maybe for the RF Cart and Loaders.

**Comment by AEnterprise** [comment]
sidenote: you do not have to keep any of this for the BC api, also for MC 1.11.2 there now is a maven you might want to use instead of having to update the api here manually

https://www.mod-buildcraft.com/maven/

**Comment by liach** [comment]
Yeah... This is just the first step.

**Comment by liach** [comment]
@CovertJaguar I urge you to merge this pull first so that we won't get crashes and complaints for our incorrectly ported CoFH RF API.

**Comment by CovertJaguar** [comment]
Then just comment out RF completely. I'm not adding FU support.

**Pull request closed without merging**
