### PR TITLE
Serialize cart battery charge

### PR DESCRIPTION
**Pull request by liach**
Otherwise they lose power once chunk unloads.

### CODE REVIEW

**Review by CovertJaguar — COMMENTED** [review]
This works, but an argument could be made that we should add write/read functions to the battery itself and just call those.

**Comment by liach** [comment]
I originally wanted to add default methods, but since it is in the API (Java6), we can add static methods instead.

**Comment by liach** [comment]
@CovertJaguar Fixed. You need to merge the pull in the api first.

**Comment by CovertJaguar** [comment]
The API is still Java 6? I thought I gave up caring ages ago.

**Comment by liach** [comment]
I think we should keep it J6...

**Pull request merged**
