### PR TITLE
Fix loot table not customizable

### LINKED ISSUE #51: Railcraft loot cannot be removed item at a time, but pools can be removed
**Description:**
Railcraft (in quite buggy beta) doesn't allow removing specific items. Thankfully removing entire pools is doable

**Steps to reproduce:**

**Version Info (Exact versions only):**  
LootTweaker:  1.12.2-0.0.8
CraftTweaker/Minetweaker:  1.124.1.15
Forge:  14.23.5.2815
Minecraft:  1.12.2

**Logs, scripts and other useful information:**  
https://github.com/Railcraft/Railcraft/issues/1659

### LINKED ISSUE #1659: [Suggestion] Option to disable dungeon loot
**Is your feature request related to a problem? Please describe.**

A majority of the ingots, plates and gears added to dungeon loot have no use in my pack. Less loved metals like lead and aluminum were removed, and recipes that used them were changed.

Due to a myriad of issues with Railcraft, I have to leave the ingots, plates and gears enabled in the config. These items are then added to dungeon loot, which I don't like.

**Describe the solution you'd like**
Add a config option to stop Railcraft from adding loot to vanilla loot tables. The Railcraft village structure can be unaffected by this, since removing Railcraft items would leave it empty. It's mostly rails anyway. 

**Describe alternatives you've considered**
I've tried using LootTweaker to remove the items, but to be honest it's way over my head.

Disabling plates, ingots or gears in the config causes certain trades to disappear, and makes the Railcraft village chest generate empty.

Disabling the entire world generation module would probably work, but this would also remove abyssal and quarried stone which are simply too beautiful to eliminate. 

**Additional context**

### PR DESCRIPTION
**Pull request by liach**
**The Issue**
 - Fix loot table not customizable, close #1659
 - Describe the problem if an issue doesn't exist. Be as clear as possible.
 - Also resolves Daomephsta/LootTweaker#51
 
**The Proposal**
 - Use vanilla loot table loading so that we can take account of customized loot tables in data folder and other mods, etc.
 - Now can just disable the table in loottweaker
 
**Possible Side Effects**
 - The old condition is removed because vanilla just fail fast when encountering and item that does not exist (without checking any condition first, unlike recipes)
 
**Alternatives**
 - This is a minimal change. Adding too much config or details for loot tables is too much and might cause more unexpected issues.

### CODE REVIEW

**Comment by CovertJaguar** [comment]
The main problem I see here is that this removes the ability to add new pools to vanilla loot tables.

You remove the LootTableLoader, but it should probably be replaced with the updated version from Forestry described here:
Village Chests Have No Loot https://github.com/Railcraft/Railcraft/issues/983
https://github.com/ForestryMC/ForestryMC/commit/3e175aa8e6ebb10f213581ca6a80b741b00082a2

**Comment by liach** [comment]
Hmm? We are still adding loot pools to vanilla loot tables.
https://github.com/Railcraft/Railcraft/pull/1754/files#diff-9eceae9539b15a958721a4942944adf6L88
Moreover, I do not believe that we need to do url checking like forestry does. It has no real point, as loot tables can be loaded from data folder in world saves.

**Comment by CovertJaguar** [comment]
Yes we are. We only add village_workshop, the other five tables are vanilla defined, and without this code I believe they get ignored.

I don't know what you mean by URL checking, the code I linked takes the vanilla definitions and appends our pools to them.

I don't understand what tables in the data folder has to do with anything.

**Comment by liach** [comment]
hmm? we still have the ability to add new pools to vanilla pools.

**Comment by CovertJaguar** [comment]
Well at the time I wrote (or borrowed) this code, that wasn't a feature of Forge or the base game. The pools are defined currently in the Railcraft namespace. By what mechanic are they moved to the Minecraft namespace? That's what the code you removed was doing.

**Comment by CovertJaguar** [comment]
Hmm... I may have falsely assumed the code you removed was doing more than just loading the json files.

**Comment by CovertJaguar** [comment]
Now, onto the rest of the changes, you remove the ItemExistsCondition. 

This was causing the integration issues with LootTweaker?

What is the vanilla behavior when encountering an invalid item? I seem to recall it invalidated the entire loot table, not just the current pool, but my memory might be faulty.

**Comment by liach** [comment]
https://github.com/Railcraft/Railcraft/pull/1754/files#diff-9eceae9539b15a958721a4942944adf6L94

It was broken because vanilla invalidates the whole loot table when encountering an invalid item; the encounter is made before any condition is processed by the loot table loader; thus, a condition cannot prevent the invalidation.

**Comment by CovertJaguar** [comment]
Ah so the condition was pointless then.

Additionally, does per world loot table override Railcraft's loot pool additions or do they get added always? This seems to be issue #1659 and I don't see how these changes address that.

**Comment by liach** [comment]
If the per-world loot tables have blanked out Railcraft tables that contains pools that are supposed to be added to vanilla tables, the Railcraft's loot pool additions will be removed. So for loottweaker users, they just need to clear out those railcraft tables, e.g. `railcraft:chests/simple_dungeon`.

**Pull request merged**
